Document: try2pkg
Title: Debian try2pkg Manual
Author: <insert document author here>
Abstract: This manual describes what try2pkg is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/try2pkg/try2pkg.sgml.gz

Format: postscript
Files: /usr/share/doc/try2pkg/try2pkg.ps.gz

Format: text
Files: /usr/share/doc/try2pkg/try2pkg.text.gz

Format: HTML
Index: /usr/share/doc/try2pkg/html/index.html
Files: /usr/share/doc/try2pkg/html/*.html
